require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MediBlockID' do
  use_frameworks!
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    hermes_enabled: false
  )

  target 'MediBlockIDTests' do
    inherit! :complete
    # Pods for testing
  end

  dynamic_frameworks = ['Socket.IO-Client-Swift', 'Starscream', 'iProov']
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      next if dynamic_frameworks.include?(pod.name)

      puts "Overriding the static_framework? method for #{pod.name}"
      def pod.static_framework?
        true
      end

      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
